from datetime import datetime


def generate_report(
    name,
    age,
    retirement_age,
    pension,
    monthly,
    annual_return,
):

    report = f"""
AI Financial Copilot Report
===========================

Generated:
{datetime.now().strftime("%d/%m/%Y %H:%M")}

Customer Name:
{name}

Current Age:
{age}

Retirement Age:
{retirement_age}

Current Pension:
£{pension:,.2f}

Monthly Contribution:
£{monthly:,.2f}

Expected Annual Return:
{annual_return}%

---------------------------------

This report was generated by
AI Financial Copilot.
"""

    return report